export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as HowItWorks } from './HowItWorks';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as RentalComparison } from './RentalComparison';
export { default as PropertyShowcase } from './PropertyShowcase';
export { default as OwnerTestimonials } from './OwnerTestimonials';
export { default as FAQ } from './FAQ';
export { default as CTA } from './CTA';